### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by ar4s** [allegro/ralph#1450]
## Story

As a user I wanna see tabs on list view and details view.
## Criteria
- simple as f**k
- new tabs can contain extra views, list, detail form
- Define tabs by attrs in `RalphAdmin` like `list_tabs = [ComponentsView, SoftwareView]` `edit_tabs = [ComponentsView]`

**Comment by mkurek** [comment]
Possible preview (don't look at top menu):
![ralph3 0_mockups-0](https://cloud.githubusercontent.com/assets/107437/7811746/fea45c1e-03ac-11e5-9693-ecf6a944c643.png)
![ralph3 0_mockups-1](https://cloud.githubusercontent.com/assets/107437/7811747/fea86f66-03ac-11e5-9de3-003b19082024.png)

**Comment by vi4m** [comment]
Left sidebar search should be discussed. We've talked some time ago about need to have dedicated search view, because
- current search view shrinks available right page content 
- on the other hand, left search view forces you to constantly scroll down
- left sidebar is already used for navigation

Taking this into account, i would hereby propose such a feature
- quicksearch as currently which filter on all given fields
- advanced search as full-page view or covering from top as a overlay
