### ISSUE TITLE
Cable and switch management under data center

### ISSUE THREAD

**Issue by renki81** [allegro/ralph#2225]
Hi Developers

Ralph NG is a very good project. I love it.

But i miss under data center a management for switch and cable documentation.
Switch management is not so possible. But under datacenter > hardware > Generic components, would i find it great when i can here create a custom field. For example a new field for cable number and cable color or whatever.

**Comment by mkurek** [comment]
Hi @renki81 

About custom fields, we're now considering different options for that, check #2158 for details.
In terms of switch management, in Ralph 2.0 we had something called connections (between devices) and we'll probably expand this mechanism (definitely port it to Ralph NG).

**Comment by renki81** [comment]
Hi @mkurek 

Thank you for your fast reply and information.

**Comment by blacknon** [comment]
Hi Developers

I also have waiting for this functionality is implemented.
Is there progress anything?

**Comment by vi4m** [comment]
Yes, we have plans to start working on this feature in October.

**Comment by blacknon** [comment]
Thanks!

**Comment by Tibshot** [comment]
Hello,

Thank you for your amazing work.

Have any update about this feature ? Clearly, in term of datacenter management, it would be great to have this feature developed. In order to help or test, is there an available branch to pull/push some fix/feature ?

We are currently testing Ralph 'ng' branch but we can checkout another one for testing purpose.

Keep up the good work,

Tib

**Comment by vi4m** [comment]
We use one branch (ng) for the most recent changes, so it should be the base one for work.

**Comment by vi4m** [comment]
We're still waiting for some input, how this feature should be implemented in details. Any ideas / needs ?

**Comment by Tibshot** [comment]
In fact, we are thinking about switch from racktable to ralph-ng. We already setup it for testing purposes and we find it great. But there are some missing features that we would like to help to develop or specify. For us there are 3 missing features that blocks our final decision:

- Cable path. Our current discussion topic.
- Ip/Network range management (like racktable way of linking).
- Hardcoded asset's components.

So, for cable path management:

We manage every day a lot of racks/cabinets and we need a tool that reference cable plug between devices in order to see the cable path. Typically, we would like to be able to get setup cables on a patch panel and see where each cable go (another patch panel ? switch ? router ? server ? etc). I think that other providers like us could be interested with this feature. As cable can be referenced into Ralph like servers or switch are, it could be easier to 'map' a physical architecture with these informations. Moreover, for physical parts (bare metal servers, switch, routers, etc) we can imagine that could replace the 'parent' information taht we find into assets (but it introduce the multi-parent topic).

Tib

**Comment by SesquipedalianDefenestrator** [comment]
I'm only slightly familiar with Ralph at this point.  I had been looking into using Racktables to replace our cobbled-together spreadsheets and text configs, but ran across Ralph and like that it's more active and has a real API.  The ability to model network connections well is the only major "missing" feature 

I would mostly follow Racktables' example for this:
Each network connection has an optional "Remote Asset" and "Cable type".  Remote Asset is a network port on another host/switch.  So, host1's eth0 might have a remote asset of "switch1 ge1/1/", and switch1's ge1/1/1 now has a remote asset of "host1 eth0".  In the UI, it should have a link to the remote asset.

I think few people are crazy enough to track individual cables, so mostly it would just need cable type, optionally color, and length.

Bonus points for:  having an actual port/connector type on each end and for the cable.  This mostly makes sense for environments with interconnections among switches where there can be a variety of connections and cables.  10Gbase-T, 1Gbase-T, 40GBase-SR4, TwinAX, etc.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group

**Comment by Taker567** [comment]
> Hi @renki81
> 
> About custom fields, we're now considering different options for that, check #2158 for details.
> In terms of switch management, in Ralph 2.0 we had something called connections (between devices) and we'll probably expand this mechanism (definitely port it to Ralph NG).

Was the "connections" functionality from Ralph 2, as mentioned in the comment above, even been ported to Ralph 3?
We're running version 20210706.1 of Ralph 3 and cannot seem to find this functionality.
