### ISSUE TITLE
REP14: List view columns selection for user

### ISSUE THREAD

**Issue by mkurek** [allegro/ralph#2243]
# Description

As a user I want to select which columns i see on list view and bulk edit view.
# Requirements
- separated list of columns for every model (obvious :trollface:)
- developers should hardcode list of all possible columns to select (similar to `list_display`)
- there should be predefined presets of columns (ex. for business people, admins etc)
- every user can choose which columns he want to see, either directly selecting columns or choosing from one of predefined presets
- columns should properly handle fields permissions (user cannot see, or even choose, column for which he doesn't have at least read only permission)
- there should be a way to defined columns order
# Proposal of solution
## Models
- `ModelListFields` model with field for every content type (model) which is accessible through Ralph - this table should be auto-updated after every migration
- `ListFieldsPreset` model with:
  - `name`
  - `is_public` - if true, this preset could be assigned to group and choose by user; if false, it's preset created directly by user for his own needs
  - `creator` - FK to user - this could be later used to determine which presets could be chosen by user
  - `type` - choose one of `list view`, `bulk edit`, ... - this could be used to choose different presets for regular view and bulk edit
  - `model / content_type`
  - M2M relation with `ModelListFields` (notice that only fields with proper content_type, chosen before could be chosen here) with additional order (int) field
- M2M between user and `ListFieldsPreset`, with through table containing additional `content_type` field (+ unique on user and content_type)
- M2M between group and `ListFieldsPreset` - details just like above + only public presets could be chosen here.
## GUI
- we should write custom widget for selecting columns for selected (or current) content_type
- widget should support columns order (https://jqueryui.com/sortable/#default ?) 
- this widget will be use both in "admin" page for presets and in list view for single user - user will choose either one of presets (see Logic below for details) or create the new one. This widget should show only fields accessible by user. It could be shown there in modal layer?
## Logic
- preset selection for user:
  1. check is user has preset selected for current content type - if yes, select this preset, if no - move to the step 2
  2. check presets for groups that the user belongs to. if there is more than one preset, select XXX (to discuss)
  3. if user does not belong to any group or there is any preset defined for his groups, select default for this model (`list_display`)
- whatever preset is selected, user privileges should be always validated for these columns
- presets for user should be cached (until there is change either in his preset or he had chosen different preset)
# To discuss
- there is a lot of redundant data here (especially `content_type`) - we could think about other way to store this (other data model)
- what should we do when user belongs to multiple groups, all with different preset selected? How should we "promote" one preset to be default one (assuming that user doesn't have it's own preset / any chosen).
- anything not mentioned?

**Comment by vi4m** [comment]
It's very complex for a gain it gives. It gives some unpredictable behavior in some border cases, where every user has different fields sets on the display view. 

Imagine the bug, for example with the **repr**() serialization exception which occurs only on one field which is configured by one user. Debugging it will change the paradigm - to fetch given user configuration from database, or logging into his account(second password system?) And we count more and more overhead for development. I don't like mixing code and configuration in the database, starting up application to see the configuration is IMO bad idea.

I was thinking about the simplier(maybe too simple - but anyway) approach with is more limited, but let's start with the real problem:

The real problem is: 
- system administrator groups want to see particular location + "operating system version" fields view
- data center operator wants to see location information without operating system details
- finance person wants to see supports / costs fields etc

Thereby i propose to create viewsets:

# Viewsets

VIEWSETS
- visible "buttons" above the data table, accessible to everybody
- internally represent a list of fields to display for given data table / object
- configured in django/ralph internal settings, not gui
- configured by system owner, not particular user
- can be versioned, stored, cleared without a worry
- contains list of fields listed on given viewset
- appends to the "base" fields which will be always present (harcoded) for example hostname or id

Trivialized example:

VIEWSETS  = (
 ('boasset_view': [
    'financial_view' : { caption: "Finances", fields: ['status', 'barcode', 'sn', 'invoice date', 'invoice_no']},
    'operations_view' : {caption: "Locations", fields:['status', 'barcode', 'sn', 'rack', 'location', 'venture']},
    ]
)

# Validation

It's good to think about validating it during startup. It should be easy. 

# Implementing it

It' should be the easiest to implement, without disrupting much of framework - hooking into the  get_list_display(), providing default fallback if VIEWSETS[object] is not defined.

# Pros
- Easy, easy, easy, sane, configuration and code lives in the repository. 
- Don't need to run instance to configure. 
- In case of migrations can make pull request to the settings as well, easy to check in  CI  tests integration.
- Users can switch freely and verify the truth, without the 'i don't see it, how do you see it?' Can switch between various viewsets using simple "buttons" or whatever.
- Not needed to introduce another database model

# Cons

Not eye candy.

**Comment by mkurek** [comment]
Sorry @vi4m but I could not agree with you. My arguments:
- how could we do 'User preferences' without storing it in database? It's no configuration any longer, it's user preference. 
- bugs are inevitable in software development, but:
  - this bug you've mentioned will potentially never occur, because we'll limit possible choices which user can choose in source code - on the other hand this bug could occur in your case too (unless we'll validate settings during start and don't allow to start the application if config doesn't valid)
  - we'll make tests for list view with every possible column chosen to make sure if it renders correctly, just like we test if every value in current `list_display` works fine
- notice, that permissions are similar case here too - what if there is only single user which have particular permissions settings? And it could be configured in gui
- if you have multiple instances of ralph, syncing settings could be pain in the ass - here you're storing it in one place (i know, this argument is similar type to yours `Not needed to introduce another database model`, but you've started :smirk:)
- `In case of migrations can make pull request to the settings as well, easy to check in CI tests integration.` - every column user has chosen will be "validated" for single request for the list view to check if this column still exists and if user has permission to this column (permissions should be validated in your case as well), so migrations are not a problem here (we could raise warning to logs that this column does not exist anymore, but in display process, we'll ignore it)
- `Not needed to introduce another database model` - so from now we'll not make any features which requires new db models? don't think so :smile: 
-  `Users can switch freely and verify the truth, without the 'i don't see it, how do you see it?' Can switch between various viewsets using simple "buttons" or whatever.` - the same case here as for permissions - and with mine approach users could still select from one of predefined sets of columns (probably only few % of users will create their own columns-set and most of them will use predefined sets, but unlike in your idea it could be modified by admin in gui, not in settings)
- `can be versioned, stored, cleared without a worry` - if we use reversion (just like in every other model) we'll version them too (and could easily revert the changes)
- last, but not least: #1482 - you've described the idea to keep some of the settings (configuration, preferences, whatever) in database to allow to change them without administration effort

**Comment by vi4m** [comment]
Nice, that you pointed to this issue https://github.com/allegro/ralph/issues/1482 becaues i think it solves the problem - storing this configuration info not in the ralph database, nor in settings file, but in etcd daemon as we always wanted to.

**Comment by mkurek** [comment]
@vi4m sure, but:
- you'll modify this from GUI? without application restart? so we should validate it during saving, not application startup, am i right?
- introducing new db model is bad, but there is nothing wrong with introducing whole new service component (etcd)? (i'm aware that it will be used to store other configuration as well) - my point is that for now we don't have such a component (distributed key-value store) and we'll have to put a lot of effort to make it working with Ralph. Another point is, that it shouldn't be required IMO - it will complicate installation and maintenance process for most of open-source users (ex. with single instance). Coming back to original problem (columns sets), IMO it's too much tied with users groups (and even single user; db models/entities in general) to store it in etcd.

**Comment by ghost** [comment]
My definition of problem would be:
1. user can see all fields which his/her permissions allow to see and nothing more (kind of `viewsets` mentioned by @vi4m )
2. within users-allowed-permissions (`viewset`) user can control which field is visible and which is hidden

It's up to discuss if each part of such defined feature is wanted. Because "2" looks like nice-to-have or or even it could be added in near or further future.

**Comment by vi4m** [comment]
Closing this REP since it was not implemented in Ralph 3.
