### ISSUE TITLE
Customization options

### ISSUE THREAD

**Issue by trondhindenes** [allegro/ralph#2747]
Is it possible to remove classes from ralph? We need a simple cmdb just to keep track of servernames, ip addresses and some key-value pairs with metadata. Is there any documented procedure for how to configure a "minimized" version?

**Comment by jayme** [comment]
I believe you can customize the menus in `sitetrees.py`

**Comment by trondhindenes** [comment]
Thanks - I was thinking more in terms of simplifying the objects themselves - we simply don't need that many dimensions.

**Comment by vi4m** [comment]
You can hide most of the fields using permissions. There are only 3 required fields for Asset from within GUI so you can slim visible part of the system  a lot. When you grow with the system you can enable particular fields again.

**Comment by vi4m** [comment]
# Why we provide so many models / schema ?

We want to standarize objects as much as we can. So we provide a lot of models which are common in all tcp/ip networks and common dc/bo hardware.  When we standarize objects, we can provide a lot of functions on top of it. 

# I don't need it

Hiding from UI is certainly possible and encouraged using GUI (permissions) or modifying sitetree file via the code. We will document it to be even more approachable to the users.

The second strategy is to fork the Ralph project, and just remove unneded objects. But i'd like to discourage it. Why?

Keeping the schema intact  gives you ability to do future upgrades, when you need to grow. For example, many additional modules such as powerdns integration, and scrooge billing additional modules rely on "Service" field, to identify the cost owner. 

Most of the fields are optional. For example adding Asset requires adding only 3 fields.  We though twice before adding it.  So i will recomment to just hide it instead of doing the fork/schema modifications. 

# What about the other CMDB systems?

In some CMDB systems you have simple key/value store with "classes" on top of it, defined on top of it, usually xml defined.  For the first time, It sounds like a  good idea. You can expand the models itself, it's very dynamic. 

But we believe this is the reason those systems are hard to integrate with other systems, hard to modify/customize, and hard to backup. The database are mess with all these key/value based custom fields.  Another argument is that you can't rely on the beahavior of fields, because it's dynamic by nature. You can't easily build deployment / dhcp because validation when the integrity is not enforced on the database. And when you don't integrate CMDB with the operations pipeline/automation systems of your company, your system will be quickly outdated. 

Another arguments - from the developer perspecitve - if we move all the database fields to the generic key/value store we would lost beauty of code, when you can rely on subset of fields always existent, we would decrease performance, make validation much harder, would lost automatic api integration which you get for free in Ralph without writing much of code.

That's why we keep all fields explicit, in the database layer, and mandatory to run Ralph. This is the low price to pay for such a functionality pack as we have in Ralph. We encourage to hide it only on the user interface, which doesn't impact the overall experience.

# What about the performance?

Unused models doesn't affected peformance in any significant way.

**Comment by vi4m** [comment]
Did it work?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
