### ISSUE TITLE
Need help on ralph 3.0 install

### ISSUE THREAD

**Issue by tjyang** [allegro/ralph#2978]
I am testing out ralph3 also a django newbie.
Looks like I missed a step somewhere.
1. web site with only text mode display

![image](https://cloud.githubusercontent.com/assets/378638/23826993/e4e8bfc4-066e-11e7-9f64-674c7310d341.png)

2. the debug log

```
Performing system checks...

System check identified no issues (0 silenced).

Django version 1.8.17, using settings 'ralph.settings.dev'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 176-052-857
10.45.0.50 - - [11/Mar/2017 22:22:25] "GET / HTTP/1.1" 200 -
10.45.0.50 - - [11/Mar/2017 22:22:25] "GET /static/vendor/js/webcomponents-lite.js HTTP/1.1" 404 -
10.45.0.50 - - [11/Mar/2017 22:22:25] "GET /static/elements/elements-min.html HTTP/1.1" 404 -
10.45.0.50 - - [11/Mar/2017 22:22:25] "GET /static/vendor/css/foundation-datepicker.css HTTP/1.1" 404 -
10.45.0.50 - - [11/Mar/2017 22:22:25] "GET /static/css/ralph.css HTTP/1.1" 404 -
10.45.0.50 - - [11/Mar/2017 22:22:25] "GET /static/vendor/js/foundation.min.js HTTP/1.1" 404 -
10.45.0.50 - - [11/Mar/2017 22:22:25] "GET /static/vendor/js/jquery.js HTTP/1.1" 404 -
10.45.0.50 - - [11/Mar/2017 22:22:25] "GET /static/vendor/js/modernizr.js HTTP/1.1" 404 -
10.45.0.50 - - [11/Mar/2017 22:22:25] "GET /jsi18n/ HTTP/1.1" 200 -
10.45.0.50 - - [11/Mar/2017 22:22:25] "GET /static/vendor/js/webcomponents-lite.js HTTP/1.1" 404 -
10.45.0.50 - - [11/Mar/2017 22:22:26] "GET /static/vendor/js/jquery.js HTTP/1.1" 404 -
10.45.0.50 - - [11/Mar/2017 22:22:26] "GET /static/vendor/js/foundation.min.js HTTP/1.1" 404 -
10.45.0.50 - - [11/Mar/2017 22:22:26] "GET /static/vendor/js/modernizr.js HTTP/1.1" 404 -
10.45.0.50 - - [11/Mar/2017 22:22:26] "GET /static/favicons/favicon-16x16.png HTTP/1.1" 200 -

```

**Comment by tjyang** [comment]
Looks like I ran into similar issue like this post.
http://stackoverflow.com/questions/24199029/django-cannot-find-static-files-need-a-second-pair-of-eyes-im-going-crazy

**Comment by vi4m** [comment]
Which installation method ?

**Comment by tjyang** [comment]
@vi4m , Thanks for the response.
I am creating a gdoc to document the whole process of using manual installation on CentOS 7.3.
The URL is here, let me know if you want edit access beside commenting.

https://docs.google.com/document/d/1m-YLNgMwjRrlFPYaq8ITKvzdwDcEiQBOdpMfijyLw6M/edit#

I will  ping you again when the gdoc is ready for your review to ping point what went wrong.

**Comment by nvdacsheets** [comment]
The linked StackOverflow post focuses on configuring Django so that static files will be served.

Before the static files can be served, they must exist. Depending on your installation method, they may not exist initially. For example, if you start with a clone of the git repository, it appears that `gulp` must be run in order to generate various files, including `./src/ralph/static/css/ralph.css`.

`gulp` will not be available until `npm` is working. On Ubuntu 14.04, it appears that the version of `npm` packaged by Ubuntu (1.3.10~dfsg-1) is sufficient, at least to get the `n` package which provides a convenient way to get `nodejs` 6.9.2. It looks like the `npm` available in CentOS 7's EPEL is significantly newer, so I'd expect it will work fine as well.

Once `gulp` is installed, it can be run as `./node_modules/.bin/gulp` from the project directory. This appears to be sufficient to get the site working normally, at least with respect to serving static CSS and JavaScript files.

**Comment by romcheg** [comment]
Please refer to the official documentation: https://ralph-ng.readthedocs.io/en/stable/installation/installation/

**Comment by richlv** [comment]
Unfortunately the official docs do not cover RHEL family at all - perhaps the manual install instructions can be adopted in the documentation?
