### ISSUE TITLE
[SOLVED] Installation on CentOS/RHEL7

### ISSUE THREAD

**Issue by didierm** [allegro/ralph#3093]
The following procedure documents the minimum set of actions required to install the current release (20170613.1) on a pristine EPEL-enabled EL7, and run ralph as an unprivileged passwordless system user _ralph_ in a **virtualenv/nodeenv** environment with a MariaDB SQL backend instance.

As **_root_** : 

```
firewall-cmd --permanent --add-port=8000/tcp && firewall-cmd --reload

yum-config-manager --enable epel
yum install mariadb-server
systemctl start mariadb && systemctl enable mariadb

yum install gcc-c++ mariadb-devel redhat-rpm-config openldap-devel

yum install python34-pip python34-devel
useradd -d /opt/ralph -c "Ralph service account" -m -r ralph

su - ralph
```

As user **_ralph_** : 
```
(
echo "DROP DATABASE IF EXISTS ralph_ng; CREATE DATABASE ralph_ng DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
echo "CREATE USER 'ralph_ng'@'localhost' IDENTIFIED BY 'ralph_ng';"
echo "GRANT ALL PRIVILEGES ON ralph_ng.* TO ralph_ng@localhost WITH GRANT OPTION;"
echo "FLUSH PRIVILEGES;"
) | mysql -u root

pip3 install --user virtualenv
virtualenv ralph && . ~/ralph/bin/activate
echo ". ~/ralph/bin/activate" >> ~/.bashrc


pip install nodeenv
nodeenv -p
npm install -g bower
npm install -g gulp

wget https://github.com/allegro/ralph/archive/20170613.1.tar.gz
tar xf 20170613.1.tar.gz
ln -s ralph-20170613.1/ ralph-core
cd ralph-core/
make install
make install-test
gulp
ralph migrate
make menu

ralph syncdb
	(credentials: admin/admin)

RALPH_DEBUG=True ralph runserver 0.0.0.0:8000
```

Ralph now runs on the publically accessible http://admin:admin@server-ip-address:8000/

This solves issue https://github.com/allegro/ralph/issues/2978 .

**Comment by didierm** [comment]
TODO : 
- create a **systemd** service ;
- RPM package (with upgrade scripting).

**Comment by vi4m** [comment]
Thanks for this tutorial !

**Comment by vi4m** [comment]
I think we should incorporate it into our docs.

**Comment by didierm** [comment]
Be my guest : EL7 is a large ecosystem, lowering the deployment threshold can only accelerate Ralph's adoption rate in the non-Ubuntu/Docker community.

I'm sure more capable people than me can massage this into a decent RPM with proper upgrade scripting et al, making it fit for EPEL/Fedora adoption.

Thanks for Ralph !

**Comment by dlasalle** [comment]
If you guys are interested in creating RPMs for Ralph (and other package formats),  I'm working on system for building Linux packages for multiple distributions using a simplified configuration (https://bytepackager.com) which may be a good option. It's still in the early stages, but creates Arch, CentOS, Fedora, and Ubuntu packages right now, and I'd love to get any feedback or feature requests.

**Comment by steph-ben** [comment]
I would be very interested having RPM release for ralph.

My 2 cents : [fpm ](https://github.com/jordansissel/fpm)is my best friend when building simple RPMs

**Comment by vi4m** [comment]
@dlasalle great news ! Did you try to package Ralph ?

**Comment by gruselglatz** [comment]
Are there some News on the RPM Package Front?

**Comment by loganmines** [comment]
I'd also like to see an RPM - we're standardized on RHEL...

**Comment by nasir0097** [comment]
Hi there tried to run through this setup on my Centos but running into issue #2978

**Comment by romcheg** [comment]
RHEL 7 does not provide python 3 and we cannot make a package that depends on external repositories. RHEL8 Beta is available atm and it does provide python 3 package, however, we are not sure, if we are going to make a rhel package due to lack of resources. You are welcome to create a topic on [Ralph forum ](https://ralph.discourse.group) to discuss the question.

**Comment by maverick85** [comment]
So you’re not interesting in attending the professional community that uses RHEL or CentOS, because Debian is the most common platform?

Ah well, scratching this from the list.

**Comment by romcheg** [comment]
**Two vital things:** 

- We won't tolerate any (passive)aggressive language or behavior in Ralph community, so please mind your words and stay professional when posting comments here. No warnings will be given.
- I do realize it is important to have packages for all major distributions but as I've mentioned there is no way to package Ralph for CentOS/RHEL 7 because Ralph requires python-3 which is not available there. As soon as CentOS/RHEL 8 is available, it will be possible to make a package for them. However, there are less than 5 active maintainers in Ralph community and we have many other responsibilities, so our time is limited. We have done a package for Debian-based distros due to a simple fact that we need that for our production environment. We have no time for making an rpm package. Any other contributor can do that, however, an we will be happy to accept their contribution.

**Comment by richlv** [comment]
There doesn't seem to be anything wrong with having a package that would require "optional" or Red Hat Software Collections repos - but the lack of packager time is the important factor, of course :)

**Comment by romcheg** [comment]
@richlv we will of course be happy, if someone besides the maintainers could help us with RPM packaging. Would you consider doing that? My experiments with RHEL8 Beta during my free time ended up with an export hold they have put onto my account. :) As soon as I resolve the issue I will probably continue experimenting.

**Comment by maverick85** [comment]
> **Two vital things:**
> 
> * We won't tolerate any (passive)aggressive language or behavior in Ralph community, so please mind your words and stay professional when posting comments here. No warnings will be given.
> * I do realize it is important to have packages for all major distributions but as I've mentioned there is no way to package Ralph for CentOS/RHEL 7 because Ralph requires python-3 which is not available there. As soon as CentOS/RHEL 8 is available, it will be possible to make a package for them. However, there are less than 5 active maintainers in Ralph community and we have many other responsibilities, so our time is limited. We have done a package for Debian-based distros due to a simple fact that we need that for our production environment. We have no time for making an rpm package. Any other contributor can do that, however, an we will be happy to accept their contribution.

It took me a couple of months to decide to reply.
Python 3 is widely available for CentOS. You can use the most commonly used EPEL repository to get it installed in ... 2 minutes. (not so long really)
Your text makes it look like its some world revolving task to have python3 on CentOS. It is not.
Any basic good for nothing software installer now a days sets up EPEL and REMI or IUS repos and installs things that aren't available from base.
And to use it, you can use virtual environment, set python 2 as an alternative and set priority to python 3 (etc etc etc)
So... I am sorry for your lack of knowledge and for those excuses, your whole text I quoted, is very distasteful.

I wish you good riddance and hope next time you get things right before talking like some CentOS expert.

**Comment by romcheg** [comment]
@maverick85 I have spent a significant portion of my career at a company doing RPM packaging for RHEL/CentOS and besides that I was a part of the python-3 initiative team in OpenStack. In both places we had to limit our python usage to python-2 only not because it was impossible to use an extra repo but because using that repo would brake RedHat’s support agreements.

Anyway, if you’d like to see Ralph packaged for RHEL/CentOS, I would suggest you to do some useful work, which without any doubt will be reviewed and then accepted. We barely have time to do a generic package for Ubuntu which we need for our infrastructure.
If your plan is to just keep talking c**p about the maintainers or other community members I would kindly suggest you to do that in another project and never in this one.

**Comment by maverick85** [comment]
First we're not talking about RH we're talking about CENTOS. (regarding support agreements).
Second I will try to do that. Unfortunately I don't have much free time, I travel a lot for work, and sometimes I do software testing. I found Ralph to be promising, definitely congrats for the work put into it, my rant was exclusively to your reply that, again, I don't agree with the aforementioned difficulties. I have nothing against you or the community members, don't ad-hominem my argument.

Have a nice day ahead and best of luck.

**Comment by romcheg** [comment]
There are a few bigger companies that use Ralph and use RHEL as their base distribution. I’m not sure how they resolve the problem atm but I think they run Ubuntu or CentOS just for Ralph. Unfortunately when we are talking about DCIM systems like Ralph we have to deal with bigger users who actually do have their own DCs and those companies often use RHEL instead of CentOS so we have to keep in mind RedHat’s legal agreements when doing a package.

It is better to have something than nothing, so perhaps starting with a CentOS-only package is a way to go. On the other hand publishing a package like that and then pretending the problem is solved is not the way we’d like to take.

In any case — RHEL 8 has python-3 support and so will have CentOS 8. As soon as I get rid of the export hold they had put onto my account, I will try to play with it. Any contribution from other people are more than welcome, just as I mentioned.

**Comment by maverick85** [comment]
I remember seeing someone installing python3 directly on rh and using scl to enable it on some project that required it and I remembered it worked damn well. the python that was installed came directly from some RH repo too, but that was my colleague doing it I just saw him doing it can't remember all the details.
100% on the companies that have DC's have RH... setting up 200 next two weeks... lol
but will install CentOS anytime to run an application that seems worthwhile, virtualising its easy pie.

The thing here is that I don't favour debian distros for nothing. So when not on corporate I go for CentOS... too much similarity with all things red hat, I know around, not that I wouldn't get to be comfortable with debian I just don't care enough to go that way now. And I find centos much more secure than debians so far on what I can tell.

I promise if I get the time I will look into this, or try to drag a developer to it. I haven't had much time for my own personal projects... let about others... lol

cheers

**Comment by maverick85** [comment]
I remember seeing someone installing python3 directly on rh and using scl to enable it on some project that required it and I remembered it worked damn well, but can't detail how he configured.
100% on the companies that have DC's have RH... setting up 200 next two weeks... lol
but will install CentOS anytime to run an application that seems worthwhile, virtualising its easy pie.

The thing here is that I don't favour debian distros for nothing. So when not on corporate I go for CentOS... too much similarity with all things red hat, I know around, not that I wouldn't get to be comfortable with debian I just don't care enough to go that way now. And I find centos much more secure than debians so far on what I can tell. (amount of patches you need to apply to deb based distros)

I promise if I get the time I will look into this, or try to drag a developer to it. I haven't had much time for my own personal projects... let about others... lol

cheers

**Comment by richlv** [comment]
Heya, thank you all for the attention to this topic. As I haven't got to installing Ralph even once yet, for now I could at best help with package testing.

**Comment by richlv** [comment]
Were the manual install instructions included in the official documentation in the end? Planning to try them out and possibly contribute to the docs at least.

**Comment by richlv** [comment]
Getting ralph_ng running on RHEL 7.5 was a long journey, thanks to all the help in the Ralph chat - that was crucial for the final steps.

This is really not a nice way to install things, but perhaps it helps somebody - just throwing it out here.

````
sudo yum install python34-pip python34-virtualenv mariadb-devel
sudo useradd -d /opt/ralph -c "Ralph service account" -m -r ralph
sudo mysql
> CREATE DATABASE ralph_ng DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
> GRANT ALL PRIVILEGES ON ralph_ng.* TO ralph_ng@localhost identified by 'ralph';

sudo -i -u ralph python3.4 -m venv ralphvenv

echo ". ~/ralphvenv/bin/activate" | sudo tee /opt/ralph/.bashrc
sudo -i -u ralph pip install nodeenv
sudo -i -u ralph nodeenv -p --node=10.16.1
sudo -i -u ralph npm install -g bower
# gulp 4 not supported at this time
sudo -i -u ralph npm install -g gulp@^3.9.0
sudo -i -u ralph git clone https://github.com/allegro/ralph.git --single-branch ralph_ng

# the following hack needed by "make install", which hardcodes to "pip3"
# maybe can be done in venv instead, or user alias can be added?
sudo ln -s /usr/bin/pip3.4 /usr/bin/pip3

=== All the following as the ralph user:
cd ~/ralph_ng/
make install
gulp
python setup.py install
ralph syncdb
# create superuser when prompted
export DATABASE_PASSWORD='ralph'
RALPH_DEBUG=True ralph runserver 0.0.0.0:8000
````

**Comment by sarath196** [comment]
I tried all your steps on Centos7.. till ralph syncdb, but I get the following error.

`Synchronizing apps without migrations:                           
Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states...Killed
`

**Comment by Free6838** [comment]
So,  i managed to run on CentOS without any issue, but I had to modify some commands 

here's full list of commands and that might help you

```
firewall-cmd --permanent --add-port=8000/tcp && firewall-cmd --reload

yum-config-manager --enable epel
yum install mariadb-server
systemctl start mariadb && systemctl enable mariadb

yum install gcc-c++ mariadb-devel redhat-rpm-config openldap-devel

yum install python34-devel # Replace 34 with current python version installed - in my case it was 36 so i used python36-devel  pip is already installed. 
useradd -d /opt/ralph -c "Ralph service account" -m -r ralph 

su - ralph

As user ralph :

(
echo "DROP DATABASE IF EXISTS ralph_ng; CREATE DATABASE ralph_ng DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
echo "CREATE USER 'ralph_ng'@'localhost' IDENTIFIED BY 'ralph_ng';"
echo "GRANT ALL PRIVILEGES ON ralph_ng.* TO ralph_ng@localhost WITH GRANT OPTION;"
echo "FLUSH PRIVILEGES;"
) | mysql -u root

pip3 install --user virtualenv
virtualenv ralph && . ~/ralph/bin/activate
echo ". ~/ralph/bin/activate" >> ~/.bashrc


pip install nodeenv 
nodeenv -p --node=11.15.0 #using this version fixes bower hang during install and undefined primordials
npm install -g bower
npm install -g gulp

wget https://github.com/allegro/ralph/archive/20170613.1.tar.gz #Go to tags of repository and copy latest tags tar.gz url
ln -s ralph-20170613.1/ ralph-core #same, replace with correct folder name
cd ralph-core/
git init
git remote add origin https://github.com/allegro/ralph.git
git remote set-url origin https://github.com/allegro/ralph.git
git pull
git pull origin ng
git reset --hard origin/ng
make install

make install-test
gulp
ralph migrate
make menu

ralph syncdb #create superuser 
ralph runserver 0.0.0.0:8000
```

ralph server will run on server-ip:8000

if you will receive error 500 on main page, edit file 

ralph_core/src/ralph/settings/prod.py 

edit line 7 set ralph_debug  to True instead of false, that's all

**Comment by netbox2020** [comment]
Hi
I am trying to install it for Centos , what should be settings for
/etc/httpd/conf.d) and systemd 

Thanks

**Comment by andrewm659** [comment]
@Free6838  It took forever to do a a 'make install-test' and it failed.  Has anyone tried newer versions of the dependencies?

Still failing on RHEL8 and its variants. (AlmaLinux and RockyLinux)
