### ISSUE TITLE
Add photos to racks

### ISSUE THREAD

**Issue by ErikSmedinga** [allegro/ralph#3242]
I would like to add photo's to the racks in the same way as I can add attachments to data center assets. I want to be able to add multiple photo's for reference.

**Comment by romcheg** [comment]
Hi @ErikSmedinga, there is already a request for a feature like you have described in #2264. I will link these tickets to avoid duplication.

Unfortunately, the core team had to concentrate on some other important changes in Ralph, so this feature was never scheduled. Frankly, at this moment I cannot provide any estimate for it. We, however, will accept any contribution and provide contributors with necessary help and support required in order to land this sort of change to Ralph.

**Comment by romcheg** [comment]
Duplicates #2264

**Comment by ErikSmedinga** [comment]
That's nice too, but I have a different request. From time to time we take pictures of every rack. Now we have all the pictures in a separate folder. It would be nice to add the photo's to the racks in Ralph.
