### ISSUE TITLE
Plans to update for the latest Django LTS Version?

### ISSUE THREAD

**Issue by jeasoft** [allegro/ralph#3408]
Hi guys!

First of all, thank you for your awesome work with Ralph-NG, it's a very complete software.

Now I want to know if there's a plan to migrate Ralph to a newer version of Django. This is because there's not plans for more updates to Django 1.8.X and there is a risk for the security of some companies who can use Ralph outside an internal scope.

**Comment by romcheg** [comment]
We do have to do it. However, since Ralph basically overrides a lot of Django's internals and integrates those modifications with some of the external packages, it's not that simple. We will have to come up with a testing plan before making any changes and to do a hackaton for that. So the answer is Yes, there are plans but they are not clarified yet.

**Comment by crumohr** [comment]
Hi @romcheg,

a lot of time has passed, is there any way we can support with bringing the dependencies of Ralph up-to-date?
